// This file has been autogenerated from a class added in the UI designer.

using System;
using AsReaderGunSDK;
using Foundation;
using UIKit;
using System.Collections.Generic;

namespace AsReaderLR_VS
{
	public partial class EpcMaskEditViewController : UIViewController
	{
        int PICKER_VIEW_OFFSET = 0;
        int PICKER_VIEW_LENGTH = 1;

        int ALERT_VIEW_MASK = 0;

        public AsSelectMaskEPCParam selectMaskParam;
        AppDelegate appDelegate;
        List<string> pickerData = new List<string>();

        AsReaderGUNManager gunManager = AsReaderGUNManager.sharedAsReaderGUNManager();

        AsReader mReader
        {
            get => gunManager.getCurrentAsReader();
        }

		public EpcMaskEditViewController (IntPtr handle) : base (handle)
		{
		}
        public override void ViewDidLoad()
        {
            base.ViewDidLoad();
            appDelegate = (AppDelegate)UIApplication.SharedApplication.Delegate;
            pickerView.DataSource = new MyPickerViewDataSource(this);
            pickerView.Delegate = new MyPickerViewDelegate(this);
            for (int i = 0; i < appDelegate.DATA_BIT.Length; i++)
            {
                string offset = appDelegate.DATA_BIT[i];
                pickerData.Add(offset + " bit");
            }
            if (selectMaskParam != null)
            {
                int Offset = Array.IndexOf(appDelegate.DATA_BIT, selectMaskParam.Offset.ToString());
                setOffset(Offset);
                setMask(selectMaskParam.Mask);
                int Length = Array.IndexOf(appDelegate.DATA_BIT, selectMaskParam.Length.ToString());
                setLength(Length);
            }
            else
            {
                selectMaskParam = new AsSelectMaskEPCParam();
                setOffset(1);
                setLength(1);
            } 
        }
        public override void ViewWillAppear(bool animated)
        {
            base.ViewWillAppear(animated);
            gunManager.onAsReaderGUNDisconnected = () => {
                AppDelegate.dismissGlobalHUD();
                NavigationController.PopToRootViewController(true);
            };
            gunManager.onAsReaderLeftModeKeyEvent = (status) => OnAsReaderLeftModeKeyEvent(status);
            gunManager.onAsReaderRightModeKeyEvent = (status) => OnAsReaderRightModeKeyEvent(status);
        }
        bool OnAsReaderLeftModeKeyEvent(bool status)
        {
            if (mReader.IsRFIDModule && mReader.IsBarcodeModule)
            {
                return true;
            }
            return false;
        }

        bool OnAsReaderRightModeKeyEvent(bool status)
        {
            if (mReader.IsRFIDModule && mReader.IsBarcodeModule)
            {
                return true;
            }
            return false;
        }
        public override void ViewWillDisappear(bool animated)
        {
            base.ViewWillDisappear(animated);
            gunManager.init();
        }
        public override void DidReceiveMemoryWarning()
        {
            base.DidReceiveMemoryWarning();
        }
        public override bool ShouldPerformSegue(string segueIdentifier, NSObject sender)
        {
            if (segueIdentifier == "BackToSource")
            {
                int index = pickerData.IndexOf(lengthTextField.Text);
                long maskBit = long.Parse(appDelegate.DATA_BIT[index]);
                if (maskTextField.Text.Length != maskBit / 4)
                {
                    UIAlertView alert = new UIAlertView("Error", "Mask length is not valid", null, "OK", null);
                    alert.Show();
                    return false;
                }
            }
            return true;
        }
        #pragma mark - IBAction
        partial void offsetBtnTapped(NSObject sender)
        {
            pickerView.Tag = PICKER_VIEW_OFFSET;
            pickerView.ReloadAllComponents();
            if (offsetTextField.Text != "")
            {
                int index = pickerData.IndexOf(offsetTextField.Text); ;
                pickerView.Select((nint)index, 0, false);
            }
            else
            {
                pickerView.Select(0, 0, false);
            }
            pickerView.Hidden = false;
            offsetPickerTopView.Hidden = false;
        }
        partial void maskBtnTapped(NSObject sender)
        {
            MyAlertViewDelegate alertViewDelegate = new MyAlertViewDelegate(this);
            UIAlertView alert = new UIAlertView("Mask:", "Please enter mask value.", alertViewDelegate, "Cancel", null);
            alert.AlertViewStyle = UIAlertViewStyle.PlainTextInput;
            alert.GetTextField(0).KeyboardType = UIKeyboardType.ASCIICapable;
            alert.GetTextField(0).Delegate = new MyTextFieldDelegate(this);
            alert.GetTextField(0).Text = maskTextField.Text;
            alert.Tag = ALERT_VIEW_MASK;
            alert.AddButton("OK");
            alert.Show();
        }
        partial void lengthBtnTapped(NSObject sender)
        {
            pickerView.Tag = PICKER_VIEW_LENGTH;
            pickerView.ReloadAllComponents();
            if (lengthTextField.Text != "")
            {
                int index = pickerData.IndexOf(lengthTextField.Text);
                pickerView.Select((nint)index, 0, false);
            }
            else
            {
                pickerView.Select(0, 0, false);
            }
            pickerView.Hidden = false;
            lengthPickerTopView.Hidden = false;
        }
        partial void pickerCloseBtnTapped(NSObject sender)
        {
            hidePickerView();
        }
        partial void offsetPickerOkBtnTapped(NSObject sender)
        {
            long idx = pickerView.SelectedRowInComponent(0);
            setOffset((int)idx);
            hidePickerView();
        }
        partial void lengthPickerOkBtnTapped(NSObject sender)
        {
            long idx = pickerView.SelectedRowInComponent(0);
            setLength((int)idx);
            hidePickerView();
        }
        #pragma mark - Custom
        void hidePickerView()
        {
            offsetPickerTopView.Hidden = true;
            lengthPickerTopView.Hidden = true;
            pickerView.Hidden = true;
        }
        void setOffset(int index)
        {
            offsetTextField.Text = pickerData[index];
            selectMaskParam.Offset = int.Parse(appDelegate.DATA_BIT[index]);
        }
        void setMask(string mask)
        {
            maskTextField.Text = mask;
            selectMaskParam.Mask = mask;
        }
        void setLength(int index)
        {
            lengthTextField.Text = pickerData[index];
            selectMaskParam.Length = int.Parse(appDelegate.DATA_BIT[index]);
        }
        #pragma mark - UIPickerViewDelegate
        private class MyPickerViewDelegate : UIPickerViewDelegate
        {
            EpcMaskEditViewController currentViewContorller;
            public MyPickerViewDelegate(EpcMaskEditViewController controller)
            {
                currentViewContorller = controller;
            }

            public override string GetTitle(UIPickerView pickerView, nint row, nint component)
            {
                 if (pickerView.Tag == currentViewContorller.PICKER_VIEW_OFFSET)
                {
                    return currentViewContorller.pickerData[(int)row];
                }
                if (pickerView.Tag == currentViewContorller.PICKER_VIEW_LENGTH)
                {
                    return currentViewContorller.pickerData[(int)row];
                }
                return "None";
            }
        }
        private class MyPickerViewDataSource : UIPickerViewDataSource
        {
            EpcMaskEditViewController currentViewContorller;
            public MyPickerViewDataSource(EpcMaskEditViewController controller)
            {
                currentViewContorller = controller;
            }

            public override nint GetComponentCount(UIPickerView pickerView)
            {
                return 1;
            }

            public override nint GetRowsInComponent(UIPickerView pickerView, nint component)
            {
                //throw new NotImplementedException();
                if (pickerView.Tag == currentViewContorller.PICKER_VIEW_OFFSET)
                {
                    return currentViewContorller.appDelegate.DATA_BIT.Length;
                }
                if (pickerView.Tag == currentViewContorller.PICKER_VIEW_LENGTH)
                {
                    return currentViewContorller.pickerData.Count;
                }
                return 0;
            }
        }
        #pragma mark - UIAlertViewDelegate
        private class MyAlertViewDelegate : UIAlertViewDelegate
        {
            EpcMaskEditViewController currentViewContorller;
            public MyAlertViewDelegate(EpcMaskEditViewController controller)
            {
                currentViewContorller = controller;
            }

            public override void Clicked(UIAlertView alertview, nint buttonIndex)
            {
                if (alertview.Tag == currentViewContorller.ALERT_VIEW_MASK)
                {
                    if (buttonIndex == 1)
                    {
                        currentViewContorller.setMask(alertview.GetTextField(0).Text);
                    }
                }
                else
                {
                    currentViewContorller.setMask("");
                }
            }
        }
        #pragma mark - UITextViewDelegate
        private class MyTextFieldDelegate : UITextFieldDelegate
        {
            EpcMaskEditViewController currentViewContorller;
            public MyTextFieldDelegate(EpcMaskEditViewController controller)
            {
                currentViewContorller = controller;
            }

            public override bool ShouldChangeCharacters(UITextField textField, NSRange range, string replacementString)
            {
                if (range.Length == 1)
                {
                    return true;
                }
                string a = "0123456789ABCDEFabcdef";

                if (a.IndexOf(replacementString) > -1)
                {
                    string str = textField.Text + replacementString;
                    textField.Text = str.ToUpper();
                }
                return false;
            }

        }
	}
}
