// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace AsReaderLR_VS
{
	public partial class InventoryTableViewCell : UITableViewCell
	{
        
		public InventoryTableViewCell (IntPtr handle) : base (handle)
		{
		}
	}
}
