// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace AsReaderLR_VS
{
    public partial class MainButton : UIButton
    {        
        bool didInitTextLabel;
        bool isDisabled;

        UILabel textLabel;

        [Connect]
        private NSString text
        {
            get
            {
                return (NSString)GetNativeField("text");
            }
            set
            {
                SetNativeField("text", value);
            }
        }

        public override void AwakeFromNib()
        {
            base.AwakeFromNib();
        }

        public override void LayoutSubviews()
        {
            //base.LayoutSubviews();
            initTextLabel();
        }

        void initTextLabel()
        {
            if (!didInitTextLabel)
            {
                AddSubview(createTextLabel());
                didInitTextLabel = true;
            }
        }

        UILabel createTextLabel()
        {
            if (textLabel == null)
            {
                CoreGraphics.CGSize buttonSize = Bounds.Size;
                CoreGraphics.CGSize textLabelSize = new CoreGraphics.CGSize(buttonSize.Width,buttonSize.Height);
                NSMutableParagraphStyle paragraphStyle = new NSMutableParagraphStyle();
                paragraphStyle.LineHeightMultiple = (nfloat)0.80;
                NSAttributedString attributedText = new NSAttributedString(text, UIFont.SystemFontOfSize((nfloat)24.0), null, null, null, paragraphStyle);
                textLabel = new UILabel(new CoreGraphics.CGRect(10, 0, buttonSize.Width, 50));
                textLabel.Lines = 0;
                textLabel.AttributedText = attributedText;
                textLabel.Font = UIFont.FromName("Helvetica-Bold", 24);
                textLabel.TextAlignment = UITextAlignment.Left;
            }
            return textLabel;
        }

            public MainButton(IntPtr handle) : base(handle)
        {

        }

        public void disableButton()
        {
            if (!isDisabled)
            {
                isDisabled = true;
                Enabled = false;
                createTextLabel().TextColor = UIColor.Gray;
            }
        }

        public void enableButton()
        {
            if (isDisabled)
            {
                isDisabled = false;
                Enabled = true;
                createTextLabel().TextColor = UIColor.Black;
            }
        }
    }
}
