// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace AsReaderLR_VS
{
	public partial class ScanDeviceTableViewController : UITableViewController
	{
		public ScanDeviceTableViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
