// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace AsReaderLR_VS
{
	public partial class SelectionMaskTableViewCell : UITableViewCell
	{
		public SelectionMaskTableViewCell (IntPtr handle) : base (handle)
		{
		}
	}
}
